"""
Django settings for frontoffice project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

_db = os.environ.get("MEATMAGIC_DB", "")
DB_PATH = Path(_db) if _db else BASE_DIR / "db.sqlite3"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "MEATMAGIC_SECRET",
    "django-insecure-oefteq7$kb)vns$xz%nbbdvll=d10z2u4jdoc#p^&g&dxohe-l",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Off by default for internet exposure; set MEATMAGIC_DEBUG=1 for development.
DEBUG = os.environ.get("MEATMAGIC_DEBUG", "0") == "1"

ALLOWED_HOSTS = ['*']  # LAN + Cloudflare Tunnel access

# Requests arrive over Cloudflare Tunnel as plain HTTP (TLS is terminated at
# Cloudflare) with the original scheme carried in X-Forwarded-Proto. Trust that
# header so HTTPS is detected correctly (CSRF, secure cookies, etc.).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Behind Cloudflare the request is HTTPS, so Django's CSRF middleware requires
# the Origin/Referer to be an explicitly trusted origin.
CSRF_TRUSTED_ORIGINS = ["https://pos.meatmagic.org", "https://*.meatmagic.org"]


# Company branding used on receipts, invoices and printed documents.
COMPANY_NAME = "Meat Magic Enterprises LTD"
COMPANY_MOTTO = "love thy meat"
COMPANY_PHONE = "0706800800 / 0716400400"
COMPANY_ADDRESS = "P.O. BOX 83061-80100, Links Road, Nyali"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'daily_entry'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'frontoffice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sales.context_processors.company',
            ],
        },
    },
]

WSGI_APPLICATION = 'frontoffice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
