# Generated by Django 5.2.16 on 2026-08-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('opening_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='sales.item')),
            ],
            options={
                'ordering': ['date', 'item__name'],
                'unique_together': {('item', 'date')},
            },
        ),
    ]
