# Generated by Django 5.2.16 on 2026-08-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Link this payment to a specific credit sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments', to='sales.sale'),
        ),
    ]
