# Generated by Django 5.2.7 on 2026-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_payment_to_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'Mpesa'), ('CREDIT', 'Credit')], default='', max_length=10),
        ),
    ]
