# Generated by Django 5.2.16 on 2026-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_otherservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'Mpesa')], default='CASH', max_length=10),
        ),
    ]
