# Generated by Django 5.2.16 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_payment_method_to_otherservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa')], default='CASH', max_length=10),
        ),
    ]
