# Generated by Django 5.2.16 on 2026-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_payment_mode_to_creditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'Mpesa')], default='CASH', max_length=10),
        ),
    ]
