# Generated by Django 5.2.16 on 2026-08-17 12:02

from django.db import migrations, models


def backfill_sequence(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    dates = Sale.objects.values_list("date", flat=True).distinct().order_by("date")
    for date in dates:
        sales = Sale.objects.filter(date=date).order_by("id")
        for index, sale in enumerate(sales, start=1):
            sale.sequence = index
            sale.save(update_fields=["sequence"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sequence',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Per-day order number, e.g. 1, 2, 3 ...'),
        ),
        migrations.RunPython(backfill_sequence, migrations.RunPython.noop),
    ]

