# Generated by Django 5.2.16 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='customer_ctp',
            field=models.CharField(blank=True, help_text="Customer's CTP number, used to search creditors.", max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_ctp',
            field=models.CharField(blank=True, help_text="Customer's CTP number, used to search creditors.", max_length=50),
        ),
    ]
