# Generated by Django 5.2.16 on 2026-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_creditpayment_customer_ctp_sale_customer_ctp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherservice',
            name='payment_method',
            field=models.CharField(choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'Mpesa')], default='', max_length=10),
        ),
    ]
