# Generated by Django 5.2.16 on 2026-08-17 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_otherservice_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supplied', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('supplier_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(help_text='Name of the goods being supplied.', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kgs', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'Mpesa')], default='', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_supplied', '-id'],
            },
        ),
    ]
