# Generated by Django 5.2.16 on 2026-08-21 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='customer_ctp',
            field=models.CharField(blank=True, help_text='Batch reference copied from the linked credit sale.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_ctp',
            field=models.CharField(blank=True, help_text='Batch reference for this credit sale — same CTP for goods taken on the same day.', max_length=50),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('signature', models.CharField(blank=True, help_text='Internal dedupe key (sorted sale ids) so the same sales reuse one number.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales', models.ManyToManyField(related_name='invoices', to='sales.sale')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
