# Generated by Django 5.2.16 on 2026-08-31 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_supplier_payments(apps, schema_editor):
    Supplier = apps.get_model("sales", "Supplier")
    SupplierPayment = apps.get_model("sales", "SupplierPayment")
    for supplier in Supplier.objects.exclude(amount_paid=0):
        SupplierPayment.objects.create(
            supplier=supplier,
            date=supplier.date_paid or supplier.date_supplied,
            amount=supplier.amount_paid,
            payment_mode=supplier.payment_mode or "CASH",
            remarks=supplier.remarks,
            created_by=supplier.created_by,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_invoicecounter_alter_creditpayment_customer_ctp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa')], default='CASH', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RunPython(backfill_supplier_payments, migrations.RunPython.noop),
    ]
