# Generated by Django 5.2.16 on 2026-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='payment_mode',
            field=models.CharField(choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'M-Pesa')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'Mpesa')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_mode',
            field=models.CharField(choices=[('', '— Select —'), ('CASH', 'Cash'), ('MPESA', 'M-Pesa')], default='', max_length=10),
        ),
    ]
