# Generated by Django 5.2.16 on 2026-09-04 12:37

import django.db.models.deletion
from django.db import migrations, models


def backfill_creditors(apps, schema_editor):
    Creditor = apps.get_model("sales", "Creditor")
    Sale = apps.get_model("sales", "Sale")
    CreditPayment = apps.get_model("sales", "CreditPayment")

    def norm(value):
        return " ".join((value or "").split()).title()

    known = {c.name: c for c in Creditor.objects.all()}
    normalized = set(known)
    for model in (Sale, CreditPayment):
        for name in model.objects.exclude(customer_name="").values_list("customer_name", flat=True).distinct():
            n = norm(name)
            if n in normalized:
                continue
            known[n] = Creditor.objects.create(name=n)
            normalized.add(n)

    for sale in Sale.objects.exclude(customer_name=""):
        sale.creditor = known[norm(sale.customer_name)]
        sale.save(update_fields=["creditor"])
    for payment in CreditPayment.objects.exclude(customer_name=""):
        payment.creditor = known[norm(payment.customer_name)]
        payment.save(update_fields=["creditor"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_creditpayment_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Extra info: phone, address, terms, etc.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.creditor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.creditor'),
        ),
        migrations.RunPython(backfill_creditors, migrations.RunPython.noop),
    ]
