# Generated by Django 5.2.16 on 2026-09-04 14:13

from decimal import Decimal

from django.db import migrations, models


def seed_employees(apps, schema_editor):
    Employee = apps.get_model("sales", "Employee")
    defaults = {
        "Kazungu": Decimal("33000.00"),
        "Ngala": Decimal("33000.00"),
        "Famida": Decimal("25000.00"),
        "Jay": Decimal("20000.00"),
    }
    for name, salary in defaults.items():
        Employee.objects.get_or_create(
            name=name, defaults={"base_salary": salary, "active": True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_creditor_creditpayment_creditor_sale_creditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Untick to hide this employee from the salaries page.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_employees, migrations.RunPython.noop),
    ]
